-- ============================================
-- English Book Data (with SDA abbreviations)
-- ============================================

-- ---------- Bible (cid=0) ----------
-- Old Testament
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 1, 'en', 'Genesis', 'G', 'Gen');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 2, 'en', 'Exodus', 'E', 'Exod');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 3, 'en', 'Leviticus', 'L', 'Lev');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 4, 'en', 'Numbers', 'N', 'Num');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 5, 'en', 'Deuteronomy', 'D', 'Deut');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 6, 'en', 'Joshua', 'J', 'Josh');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 7, 'en', 'Judges', 'J', 'Judg');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 8, 'en', 'Ruth', 'R', 'Ruth');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 9, 'en', '1 Samuel', '1', '1 Sam');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 10, 'en', '2 Samuel', '2', '2 Sam');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 11, 'en', '1 Kings', '1', '1 Kgs');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 12, 'en', '2 Kings', '2', '2 Kgs');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 13, 'en', '1 Chronicles', '1', '1 Chr');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 14, 'en', '2 Chronicles', '2', '2 Chr');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 15, 'en', 'Ezra', 'E', 'Ezra');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 16, 'en', 'Nehemiah', 'N', 'Neh');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 17, 'en', 'Esther', 'E', 'Esth');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 18, 'en', 'Job', 'J', 'Job');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 19, 'en', 'Psalms', 'P', 'Ps');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 20, 'en', 'Proverbs', 'P', 'Prov');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 21, 'en', 'Ecclesiastes', 'E', 'Eccl');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 22, 'en', 'Song of Solomon', 'S', 'Song');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 23, 'en', 'Isaiah', 'I', 'Isa');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 24, 'en', 'Jeremiah', 'J', 'Jer');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 25, 'en', 'Lamentations', 'L', 'Lam');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 26, 'en', 'Ezekiel', 'E', 'Ezek');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 27, 'en', 'Daniel', 'D', 'Dan');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 28, 'en', 'Hosea', 'H', 'Hos');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 29, 'en', 'Joel', 'J', 'Joel');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 30, 'en', 'Amos', 'A', 'Amos');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 31, 'en', 'Obadiah', 'O', 'Obad');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 32, 'en', 'Jonah', 'J', 'Jonah');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 33, 'en', 'Micah', 'M', 'Mic');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 34, 'en', 'Nahum', 'N', 'Nah');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 35, 'en', 'Habakkuk', 'H', 'Hab');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 36, 'en', 'Zephaniah', 'Z', 'Zeph');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 37, 'en', 'Haggai', 'H', 'Hag');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 38, 'en', 'Zechariah', 'Z', 'Zech');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 39, 'en', 'Malachi', 'M', 'Mal');

-- New Testament
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 40, 'en', 'Matthew', 'M', 'Matt');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 41, 'en', 'Mark', 'M', 'Mark');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 42, 'en', 'Luke', 'L', 'Luke');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 43, 'en', 'John', 'J', 'John');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 44, 'en', 'Acts', 'A', 'Acts');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 45, 'en', 'Romans', 'R', 'Rom');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 46, 'en', '1 Corinthians', '1', '1 Cor');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 47, 'en', '2 Corinthians', '2', '2 Cor');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 48, 'en', 'Galatians', 'G', 'Gal');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 49, 'en', 'Ephesians', 'E', 'Eph');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 50, 'en', 'Philippians', 'P', 'Phil');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 51, 'en', 'Colossians', 'C', 'Col');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 52, 'en', '1 Thessalonians', '1', '1 Thess');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 53, 'en', '2 Thessalonians', '2', '2 Thess');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 54, 'en', '1 Timothy', '1', '1 Tim');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 55, 'en', '2 Timothy', '2', '2 Tim');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 56, 'en', 'Titus', 'T', 'Titus');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 57, 'en', 'Philemon', 'P', 'Phlm');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 58, 'en', 'Hebrews', 'H', 'Heb');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 59, 'en', 'James', 'J', 'Jas');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 60, 'en', '1 Peter', '1', '1 Pet');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 61, 'en', '2 Peter', '2', '2 Pet');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 62, 'en', '1 John', '1', '1 John');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 63, 'en', '2 John', '2', '2 John');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 64, 'en', '3 John', '3', '3 John');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 65, 'en', 'Jude', 'J', 'Jude');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (0, 66, 'en', 'Revelation', 'R', 'Rev');

-- ---------- SDA Books (cid=1) with abbreviations ----------
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 78, 'en', 'Counsels on Sabbath School Work', 'C', 'CSW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 79, 'en', 'Testimonies on Sabbath-School Work', 'T', 'TSSW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 16, 'en', 'Evangelism', 'E', 'Ev');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 46, 'en', "Peter's Counsel to Parents", 'P', 'PCP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 171, 'en', 'Notebook Leaflets, vol. 1', 'N', 'NL1');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 172, 'en', 'Notebook Leaflets, vol. 2', 'N', 'NL2');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 14, 'en', 'Gospel Workers', 'G', 'GW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 15, 'en', 'Gospel Workers 1892', 'G', 'GW92');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 23, 'en', 'City Evangelism', 'C', 'CEv');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 84, 'en', 'The Sanctified Life', 'T', 'SL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 88, 'en', 'The Upward Look', 'T', 'UL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 129, 'en', 'Our High Calling', 'O', 'OHC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 135, 'en', 'The Morning Star', 'T', 'TMS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 47, 'en', 'An Appeal to Mothers', 'A', 'AAM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 109, 'en', 'Christ Triumphant', 'C', 'CT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 136, 'en', 'Pamphlets', 'P', 'Pam');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 42, 'en', 'Child Guidance', 'C', 'CG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 12, 'en', 'Thoughts from the Mount of Blessing', 'T', 'TMB');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 27, 'en', 'The Ministry of Healing', 'T', 'MH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 44, 'en', 'The Adventist Home', 'T', 'AH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 110, 'en', 'Conflict and Courage', 'C', 'CC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 18, 'en', 'Counsels on Stewardship', 'C', 'CS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 19, 'en', 'Counsels to the Church', 'C', 'CCh');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 20, 'en', 'Testimonies to Ministers and Gospel Workers', 'T', 'TM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 25, 'en', 'Historical Sketches of the Foreign Missions', 'H', 'HS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 45, 'en', 'Messages to Young People', 'M', 'MYP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 48, 'en', 'Letters to Young Lovers', 'L', 'LYL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 56, 'en', 'Counsels to Writers and Editors', 'C', 'CWE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 70, 'en', 'Testimonies to Southern Africa', 'T', 'TSA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 111, 'en', 'Lift Him Up', 'L', 'LHU');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 72, 'en', 'Life Sketches of Ellen G. White', 'L', 'LS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 130, 'en', 'In the Image of God', 'I', 'IIG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 175, 'en', 'Ellen G. White in Australia', 'E', 'EGWA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 11, 'en', "Christ's Object Lessons", 'C', 'COL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 17, 'en', 'Christian Service', 'C', 'ChS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 21, 'en', 'Christian Leadership', 'C', 'ChL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 29, 'en', 'Counsels on Health', 'C', 'CH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 33, 'en', 'Healthful Living', 'H', 'HL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 36, 'en', 'Christian Temperance and Bible Hygiene', 'C', 'CTBH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 38, 'en', 'Education', 'E', 'Ed');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 39, 'en', 'Fundamentals of Christian Education', 'F', 'FCE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 40, 'en', 'Christian Education', 'C', 'CE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 41, 'en', 'Counsels on Education', 'C', 'COE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 43, 'en', 'Special Testimonies on Education', 'S', 'STE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 61, 'en', 'Testimonies for the Church, vol. 1', 'T', '1T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 62, 'en', 'Testimonies for the Church, vol. 2', 'T', '2T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 63, 'en', 'Testimonies for the Church, vol. 3', 'T', '3T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 64, 'en', 'Testimonies for the Church, vol. 4', 'T', '4T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 65, 'en', 'Testimonies for the Church, vol. 5', 'T', '5T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 66, 'en', 'Testimonies for the Church, vol. 6', 'T', '6T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 67, 'en', 'Testimonies for the Church, vol. 7', 'T', '7T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 68, 'en', 'Testimonies for the Church, vol. 8', 'T', '8T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 69, 'en', 'Testimonies for the Church, vol. 9', 'T', '9T');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 71, 'en', 'Christian Experience and Teachings', 'C', 'CET');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 80, 'en', 'Christ in His Sanctuary', 'C', 'CHS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 107, 'en', 'The Story of Redemption', 'T', 'SR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 112, 'en', 'My Life Today', 'M', 'MLT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 113, 'en', 'Today with God', 'T', 'TWG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 114, 'en', 'With God at Dawn', 'W', 'WGD');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 167, 'en', 'Redemption', 'R', 'Red');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 115, 'en', 'A Cheerful Religion', 'A', 'ACR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 3, 'en', 'The Desire of Ages', 'T', 'DA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 22, 'en', 'Pastoral Ministry', 'P', 'PaM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 24, 'en', 'The Southern Work', 'T', 'TSW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 30, 'en', 'Counsels on Diet and Foods', 'C', 'CDF');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 32, 'en', 'The Health Food Ministry', 'T', 'HFM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 35, 'en', 'Temperance', 'T', 'Temp');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 50, 'en', 'Testimonies on Sexual Behavior, Adultery, and Divorce', 'T', 'TSB');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 54, 'en', 'Counsels on Publishing Work', 'C', 'CPW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 73, 'en', 'Prayer', 'P', 'Pr');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 74, 'en', 'The Truth About Angels', 'T', 'TTA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 76, 'en', 'Welfare Ministry', 'W', 'WM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 86, 'en', 'Darkness Before Dawn', 'D', 'DBD');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 116, 'en', 'Early Morning Devotional', 'E', 'EMD');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 174, 'en', 'Loma Linda Messages', 'L', 'LLM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 49, 'en', "Mother's Letters", 'M', 'ML');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 81, 'en', 'Last Day Events', 'L', 'LDE');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 117, 'en', 'Ye Shall Receive Power', 'Y', 'YRP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 137, 'en', 'The Review and Herald', 'T', 'RH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 118, 'en', "God's Amazing Grace", 'G', 'GAG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 138, 'en', "The Youth's Instructor", 'T', 'YI');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 4, 'en', 'The Acts of the Apostles', 'T', 'AA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 5, 'en', 'The Great Controversy', 'T', 'GC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 55, 'en', 'Manual for Canvassers', 'M', 'MC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 82, 'en', 'Daughters of God', 'D', 'DG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 100, 'en', 'Spiritual Gifts, vol. 1', 'S', '1SG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 101, 'en', 'Spiritual Gifts, vol. 2', 'S', '2SG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 102, 'en', 'Spiritual Gifts, vol. 3', 'S', '3SG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 103, 'en', 'Spiritual Gifts, vol. 4a', 'S', '4aSG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 104, 'en', 'Spiritual Gifts, vol. 4b', 'S', '4bSG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 106, 'en', 'Sketches from the Life of Paul', 'S', 'SLP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 119, 'en', 'Sons and Daughters of God', 'S', 'SDG');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 120, 'en', 'That I May Know Him', 'T', 'TIMKH');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 90, 'en', 'Heaven', 'H', 'Hvn');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 121, 'en', 'The Father’s Care', 'T', 'TFC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 169, 'en', 'Special Testimonies, Series A', 'S', 'STA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 170, 'en', 'Special Testimonies, Series B', 'S', 'STB');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 52, 'en', 'The Publishing Ministry', 'T', 'PM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 53, 'en', 'Colporteur Ministry', 'C', 'CM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 122, 'en', 'Homeward Bound', 'H', 'HB');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 140, 'en', 'Manuscript Releases, vol. 1', 'M', '1MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 141, 'en', 'Manuscript Releases, vol. 2', 'M', '2MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 142, 'en', 'Manuscript Releases, vol. 3', 'M', '3MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 143, 'en', 'Manuscript Releases, vol. 4', 'M', '4MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 144, 'en', 'Manuscript Releases, vol. 5', 'M', '5MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 145, 'en', 'Manuscript Releases No. 311', 'M', 'MR311');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 146, 'en', 'Manuscript Releases, vol. 6', 'M', '6MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 147, 'en', 'Manuscript Releases, vol. 7', 'M', '7MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 148, 'en', 'Manuscript Releases, vol. 8', 'M', '8MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 149, 'en', 'Manuscript Releases, vol. 9', 'M', '9MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 150, 'en', 'Manuscript Releases No. 728', 'M', 'MR728');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 151, 'en', 'Manuscript Releases No. 760', 'M', 'MR760');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 152, 'en', 'Manuscript Releases, vol. 10', 'M', '10MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 153, 'en', 'Manuscript Releases, vol. 11', 'M', '11MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 154, 'en', 'Manuscript Releases No. 852', 'M', 'MR852');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 155, 'en', 'Manuscript Releases, vol. 12', 'M', '12MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 156, 'en', 'Manuscript Releases No. 926', 'M', 'MR926');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 157, 'en', 'Manuscript Releases, vol. 13', 'M', '13MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 158, 'en', 'Manuscript Releases No. 1033', 'M', 'MR1033');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 159, 'en', 'Manuscript Releases, vol. 14', 'M', '14MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 160, 'en', 'Manuscript Releases, vol. 15', 'M', '15MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 161, 'en', 'Manuscript Releases, vol. 16', 'M', '16MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 162, 'en', 'Manuscript Releases, vol. 17', 'M', '17MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 163, 'en', 'Manuscript Releases, vol. 18', 'M', '18MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 164, 'en', 'Manuscript Releases, vol. 19', 'M', '19MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 165, 'en', 'Manuscript Releases, vol. 20', 'M', '20MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 166, 'en', 'Manuscript Releases, vol. 21', 'M', '21MR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 1, 'en', 'Patriarchs and Prophets', 'P', 'PP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 2, 'en', 'Prophets and Kings', 'P', 'PK');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 13, 'en', 'Steps to Christ', 'S', 'SC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 37, 'en', 'Mind, Character, and Personality', 'M', 'MCP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 75, 'en', 'Faith and Works', 'F', 'FW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 77, 'en', 'Country Living', 'C', 'CL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 89, 'en', 'The New Life', 'T', 'TNL');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 93, 'en', 'Selected Messages, Book 1', 'S', '1SM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 94, 'en', 'Selected Messages, Book 2', 'S', '2SM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 95, 'en', 'Selected Messages, Book 3', 'S', '3SM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 123, 'en', 'The Voice of Prophecy', 'T', 'VOP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 124, 'en', 'Reflecting Christ', 'R', 'RC');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 125, 'en', 'The Faith I Live By', 'T', 'FLB');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 139, 'en', 'Present Truth', 'P', 'PT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 168, 'en', 'Tracts', 'T', 'Tr');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 28, 'en', 'Medical Ministry', 'M', 'MM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 31, 'en', 'A Call to Medical Evangelism and Health Education', 'A', 'CME');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 34, 'en', 'Testimonies on Diet and Foods', 'T', 'TDF');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 51, 'en', 'The Retirement Years', 'T', 'RY');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 57, 'en', 'The Philosophy of Music', 'T', 'POM');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 83, 'en', 'The Voice in Speech and Song', 'T', 'VSS');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 91, 'en', 'A Solemn Appeal', 'A', 'ASA');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 96, 'en', 'The Spirit of Prophecy, vol. 1', 'T', '1SP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 97, 'en', 'The Spirit of Prophecy, vol. 2', 'T', '2SP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 98, 'en', 'The Spirit of Prophecy, vol. 3', 'T', '3SP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 99, 'en', 'The Spirit of Prophecy, vol. 4', 'T', '4SP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 108, 'en', 'The Story of Jesus', 'T', 'SJ');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 126, 'en', 'In Heavenly Places', 'I', 'HP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 131, 'en', 'Jesus, Name Above All Names', 'J', 'JNAAN');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 134, 'en', 'The Ellen G. White 1888 Materials', 'T', '1888');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 173, 'en', 'A Place Called Oakwood', 'A', 'APCO');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 26, 'en', 'Early Writings', 'E', 'EW');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 58, 'en', 'Testimony Treasures, vol. 1', 'T', '1TT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 59, 'en', 'Testimony Treasures, vol. 2', 'T', '2TT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 60, 'en', 'Testimony Treasures, vol. 3', 'T', '3TT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 85, 'en', 'To the Little Flock', 'T', 'TLF');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 87, 'en', 'The Lord Has Promised', 'T', 'LHP');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 92, 'en', 'Confrontation', 'C', 'Conf');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 105, 'en', 'True Revival', 'T', 'TR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 127, 'en', 'Christ Revealed', 'C', 'CR');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 128, 'en', 'Maranatha', 'M', 'Mar');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 132, 'en', 'Sermons and Talks, vol. 1', 'S', '1SAT');
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (1, 133, 'en', 'Sermons and Talks, vol. 2', 'S', '2SAT');

-- ---------- General Books (cid=2) ----------
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (2, 4, 'en', 'Joshua White', 'J', NULL);
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (2, 2, 'en', 'Study on Fundamentals of Christian Education', 'S', NULL);
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (2, 1, 'en', 'Guide to True Education', 'G', NULL);
INSERT OR IGNORE INTO book_i18n (cid, book_id, lang_code, name, title, abbreviation) VALUES (2, 3, 'en', 'Lessons from Nature', 'L', NULL);
